name: ActionsTest

on:
  schedule:
    - cron: '0 3 * * *'  # 日本時間12時
    - cron: '0 6 * * *'  # 日本時間15時
    - cron: '0 9 * * *'  # 日本時間18時
    - cron: '0 12 * * *' # 日本時間21時

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install pytz
          pip install matplotlib
          pip install numpy
          pip install requests
          pip install openai
          pip install python-dotenv
          pip install sqlalchemy

      - name: Run main.py
        run: |
          python main.py
